---
title: JPE Replication Report
date: today
number-sections: true
format:
  html: default
---

# Paper Identification

|  |   |
| ---  |  -------|
| ID  |   |
| Author  |  Palagi, Valpreda |
| Title  |  U.S. Monetary Policy Spillovers and European Distributional Effects |
| Iteration |  round 1 |


::: {.callout-tip}

# Summary

In assessing compliance with our [Data and Code Availability Policy](https://www.journals.uchicago.edu/journals/jpe/datapolicy), our reproducibility team has identified the following issues, which we ask you to address:

1. Data Editor's first point.
2. Data Editor's second point.

# General


- [x] Data Availability and Provenance Statements
  - [x] Statement about Rights - Part 1: Right to use the data (e.g. *did the authors lawfully obtain the data*)
  - [x] Statement about Rights - Part 2: Right to publish the data (e.g. *are human subjects involved and did permission been granted to publish their data?*)
  - [ ] License for Data (optional, but recommended)
  - [x] Details on each Data Source
- [x] Dataset list
- [x] Computational requirements
  - [x] Software Requirements
  - [X] Controlled Randomness (as necessary)
  - [ ] Memory, Runtime, and Storage Requirements
- [x] Description of programs/code
  - [ ] License for Code (Optional, but recommended) 
- [x] Instructions to Replicators
  - [x] Details (as necessary)
- [x] List of tables and programs
- [x] References (Optional, but recommended) 


# High-level Description of Research Project


*This research project...*

- [x] uses observational data.
- [ ] uses *confidential* observational data.
- [ ] uses data generated via experiment or trial by the authors (in field or lab).
  - [ ] For lab experiments: The code to implement the experimental protocol (z-Tree, o-Tree etc) is included in the package.
  - [ ] A PDF copy of IRB approval is contained in the package.
  - [ ] A PDF document outlining the design of the experiment, including information on the selection and eligibility of participants is included.
  - [ ] A PDF copy of the instructions given to participants in both original language and an English translation is included.
- [ ] uses data generated via survey by the authors (in field or online)
  - [ ] The programs used to administer the survey (e.g. qualtrics survey file) are included.
  - [ ] A PDF copy of IRB approval is contained in the package.
  - [ ] A PDF of the original questionaire(s) and information on the selection and eligibility of participants is included.
- [ ] is a simulation study: the data are generated by an algorithm.
- [ ] is a numerical illustration: no data are used but code is used to produce illustrative output (tables, figures)


# Data description

## Data Sources


| file/name                    | public | private | DOI/URL | Access described| cited readme | cited paper |
| ----                         | ---    | ---     | ---     | ---             | ----         | ----        | 
| excel/raw/data_filtered.xlsx | yes    | no      | no      | no              | yes          | -           |
| excel/raw/data.xlsx          | yes    | no      | no      | no              | yes          | -           |


> For both input data, the following applies:

- [ ] Dataset is provided in public deposit
- [ ] Dataset is PRIVATELY provided (not for publication)
- [ ] DOI or URL is provided
- [ ] Access conditions are described:
   - [x] No information on access conditions.
- [ ] Data are not cited, but a working paper, article, or other document is cited (not a data citation)
- [] Data are cited
  - [] in the manuscript
  - [] in the README:

**In particular**, the two input files are a mixture of different sources (FRED, ECB, OECD, research papers...). However, references are incomplete, unclear and it is not explained where to download such files, nor is given a link to access them. 




# Requirements 

- [x] README is in TXT, MD, or PDF format
- [x] README is accessible at the root of the package (not inside a folder)
- [ ] Title conforms to guidance (starts with "Data and Code for: Title of Paper" or "Code for: Title of Paper", is properly capitalized)
- [x] Authors (with affiliations) are listed in the same order as on the paper

> {REQUIRED} Please review the title of the deposit as per our guidelines.



## Stated Requirements


- [ ] No requirements specified
- [x] Software Requirements specified as follows:
  - MATLAB v. R2025b
  - MATLAB toolboxes: Econometric Toolbox
- [ ] Computational Requirements specified as follows:
  - Cluster size, etc.
- [x] Time Requirements specified as follows:
  - Length of necessary computation (hours, weeks, etc.)

- [ ] Requirements are complete.


For missing requirements, see the list of required changes in @sec-findings


Software Requirements (as from the README)
• MATLAB: version used R2025b.v
• Required MATLAB toolboxes: Econometrics Toolbox.
• Operating system used for the last run: macOS.
• Included external dependencies: functions in code/routines and code/routines/subroutines. Some subroutines
refer to the Panel Data Toolbox. The appendix scripts write to code/appendix/results_appendix.


# Analyzing Data and Code Files

{{< include generated/report-pii.md >}}

{{< include generated/report-file-paths.md >}}

{{< include generated/report-duplicates.md >}}

{{< include generated/report-zero-files.md >}}

{{< include generated/report-large-files.md >}}



## Code description

{{< include generated/report-cloc.md >}}


- [x] The replication package contains a "main" or "master" file(s) which calls all other auxiliary programs.

## Computing Environment of the Replicator



- Mac Laptop M3 MacBook Air, MacOS Tahoe 26.5.1, 8 GB of memory, (M3 Processor, 8 cores)

- Matlab R2026a, with Econometric Toolbox installed

# Replication



- Downloaded code and data from zenodo.
- Commited code to git repo.
- Ran code as per README. Everything worked except the the last passage (code/appendix/figureA3.m). Last appendix figure did not reproduced. 


```R
error: >> figureA3
Unrecognized function or variable 'irf_fed'.

Error in figureA3 (line 5)
H = 0:length(irf_fed)-1;
```


# Findings {#sec-findings}

All figures, datasets, tables replicate, except `code/appendix/results_appendix/comparison_downside_risk_US_FED_vs_ECB.png`. Code error is described below.

```R
error: >> figureA3
Unrecognized function or variable 'irf_fed'.

Error in figureA3 (line 5)
H = 0:length(irf_fed)-1;
```

No more comments to be added.



## Data Preparation Code

- Program `code/quantile_regr/main.m` ran without error, produced expected output
- Program `code/appendix/quantile_regr_usa.m` ran without error, produced expected output

## Tables and Figures

| Data Preparation Program                        | Dataset created                               | Reproduced? |             |
|-------------------------------------------------|-----------------------------------------------|-------------|-------------|
| code/quantile_regr/data_build.m                 | code/appendix/results_appendix/pred_q_usa.mat | Yes         |             |
| code/quantile_regr/data_build.m                 | yy.mat                                        | Yes         |             |
|                                                 |                                               |             |             |
| Figure/Table #                                  | Program                                       | Line Number | Reproduced? |
| Table 1                                         | code/quantile_regr/table1.m                   | 40          | Yes         |
| Table 2                                         | code/quantile_regr/table2.m                   | 467         | Yes         |
| Figure 1Q                                       | quantile_regr/figure1.m                       | 57          | Yes         |
| Figure 1                                        | code/figures/figure1.m                        | 90          | Yes         |
| Figure 2                                        | code/figures/figure2.m                        | 96          | Yes         |
| Figure 3                                        | code/figures/figure2.m                        | 151         | Yes         |
| Figure 4                                        | code/figures/figure5.m                        | 89          | Yes         |
| Figure 5                                        | code/figures/figure5.m                        | 144         | Yes         |
| Figure 6                                        | code/figures/figure3.m                        | 77          | Yes         |
| Figure 7                                        | code/figures/figure4.m                        | 74          | Yes         |
| Figure 8                                        | code/figures/figure7.m                        | 66          | Yes         |
| down_up_USA.png                                 | code/appendix/quantile_regr_usa.m             | 109         | Yes         |
| linear_downside_risk_irf_USA.png                | code/appendix/figureA11_usa.m                 | 101         | Yes         |
| comparison_downside_risk_vs_avg_irf_USA.png     | code/appendix/figureA11_usa.m                 | 157         | Yes         |
| linear_downside_risk_irf_USA_ECB.png            | code/appendix/figureA1_usa.m                  | 92          | Yes         |
| comparison_downside_risk_vs_avg_irf_USA_ECB.png | code/appendix/figureA1_usa.m                  | 146         | Yes         |
| linear_downside_risk_irf_INFO.png               | code/appendix/figureA2_info.m                 | 102         | Yes         |
| comparison_downside_risk_vs_avg_irf_INFO.png    | code/appendix/figureA2_info.m                 | 157         | Yes         |
| comparison_downside_risk_US_FED_vs_ECB.png      | code/appendix/figureA3_info.m                 | 70          | No          |
|                                                 |                                               |             |             |
| In-text numbers                                 | Program                                       | Line Number | Reproduced? |


All reproduced figures look the same.
Could not reproduce entirely `comparison_downside_risk_US_FED_vs_ECB.png `

## In-Text Numbers

- [ ] In-text numbers not verified.

- [x] There are no in-text numbers, or all in-text numbers stem from tables and figures.

- [ ] There are in-text numbers, but they are not identified in the code

- Page 21, line 5: Same

## Other Issues

- Title of the Readme does not match title of the paper. 

- Input data are not cited

- Working folder has to be manually set by the replicator, there is no any line of code to run. It is an easy procedure, but it should be set inside the master file instead.


# Classification

- [ ] full reproduction
- [x] full reproduction with minor issues
- [ ] partial reproduction (see above)
- [ ] not able to reproduce most or all of the results (reasons see above)

## Reason for incomplete reproducibility


- [ ] None.
- [x] `Discrepancy in output` (either figures or numbers in tables or text differ)
- [ ] `Bugs in code` that were fixable by the replicator (but should be fixed in the final deposit)
- [ ] `Code missing`, in particular if it prevented the replicator from completing the reproducibility check
  - [ ] `Data preparation code missing` should be checked if the code missing seems to be data preparation code
- [ ] `Code not functional` is more severe than a simple bug: it prevented the replicator from completing the reproducibility check
- [ ] `Software not available to replicator` may happen for a variety of reasons, but in particular (a) when the software is commercial, and the replicator does not have access to a licensed copy, or (b) the software is open-source, but a specific version required to conduct the reproducibility check is not available.
- [ ] `Insufficient time available to replicator` is applicable when (a) running the code would take weeks or more (b) running the code might take less time if sufficient compute resources were to be brought to bear, but no such resources can be accessed in a timely fashion (c) the replication package is very complex, and following all (manual and scripted) steps would take too long.
- [ ] `Data missing` is marked when data *should* be available, but was erroneously not provided, or is not accessible via the procedures described in the replication package
- [ ] `Data not available` is marked when data requires additional access steps, for instance purchase or application procedure. 
- [ ] `Missing README` is marked if there is no README to guide the replicator, or the README is not in compliance with JPE requirements


{{< include generated/report-pii.md >}}

